<?php
namespace AwsSDK\Swf;

use AwsSDK\AwsClient;

/**
 * Amazon Simple Workflow Service (Amazon SWF) client.
 *
 * @method \AwsSDK\Result countClosedWorkflowExecutions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise countClosedWorkflowExecutionsAsync(array $args = [])
 * @method \AwsSDK\Result countOpenWorkflowExecutions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise countOpenWorkflowExecutionsAsync(array $args = [])
 * @method \AwsSDK\Result countPendingActivityTasks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise countPendingActivityTasksAsync(array $args = [])
 * @method \AwsSDK\Result countPendingDecisionTasks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise countPendingDecisionTasksAsync(array $args = [])
 * @method \AwsSDK\Result deprecateActivityType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deprecateActivityTypeAsync(array $args = [])
 * @method \AwsSDK\Result deprecateDomain(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deprecateDomainAsync(array $args = [])
 * @method \AwsSDK\Result deprecateWorkflowType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deprecateWorkflowTypeAsync(array $args = [])
 * @method \AwsSDK\Result describeActivityType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeActivityTypeAsync(array $args = [])
 * @method \AwsSDK\Result describeDomain(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDomainAsync(array $args = [])
 * @method \AwsSDK\Result describeWorkflowExecution(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeWorkflowExecutionAsync(array $args = [])
 * @method \AwsSDK\Result describeWorkflowType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeWorkflowTypeAsync(array $args = [])
 * @method \AwsSDK\Result getWorkflowExecutionHistory(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getWorkflowExecutionHistoryAsync(array $args = [])
 * @method \AwsSDK\Result listActivityTypes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listActivityTypesAsync(array $args = [])
 * @method \AwsSDK\Result listClosedWorkflowExecutions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listClosedWorkflowExecutionsAsync(array $args = [])
 * @method \AwsSDK\Result listDomains(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDomainsAsync(array $args = [])
 * @method \AwsSDK\Result listOpenWorkflowExecutions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listOpenWorkflowExecutionsAsync(array $args = [])
 * @method \AwsSDK\Result listWorkflowTypes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listWorkflowTypesAsync(array $args = [])
 * @method \AwsSDK\Result pollForActivityTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise pollForActivityTaskAsync(array $args = [])
 * @method \AwsSDK\Result pollForDecisionTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise pollForDecisionTaskAsync(array $args = [])
 * @method \AwsSDK\Result recordActivityTaskHeartbeat(array $args = [])
 * @method \GuzzleHttp\Promise\Promise recordActivityTaskHeartbeatAsync(array $args = [])
 * @method \AwsSDK\Result registerActivityType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise registerActivityTypeAsync(array $args = [])
 * @method \AwsSDK\Result registerDomain(array $args = [])
 * @method \GuzzleHttp\Promise\Promise registerDomainAsync(array $args = [])
 * @method \AwsSDK\Result registerWorkflowType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise registerWorkflowTypeAsync(array $args = [])
 * @method \AwsSDK\Result requestCancelWorkflowExecution(array $args = [])
 * @method \GuzzleHttp\Promise\Promise requestCancelWorkflowExecutionAsync(array $args = [])
 * @method \AwsSDK\Result respondActivityTaskCanceled(array $args = [])
 * @method \GuzzleHttp\Promise\Promise respondActivityTaskCanceledAsync(array $args = [])
 * @method \AwsSDK\Result respondActivityTaskCompleted(array $args = [])
 * @method \GuzzleHttp\Promise\Promise respondActivityTaskCompletedAsync(array $args = [])
 * @method \AwsSDK\Result respondActivityTaskFailed(array $args = [])
 * @method \GuzzleHttp\Promise\Promise respondActivityTaskFailedAsync(array $args = [])
 * @method \AwsSDK\Result respondDecisionTaskCompleted(array $args = [])
 * @method \GuzzleHttp\Promise\Promise respondDecisionTaskCompletedAsync(array $args = [])
 * @method \AwsSDK\Result signalWorkflowExecution(array $args = [])
 * @method \GuzzleHttp\Promise\Promise signalWorkflowExecutionAsync(array $args = [])
 * @method \AwsSDK\Result startWorkflowExecution(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startWorkflowExecutionAsync(array $args = [])
 * @method \AwsSDK\Result terminateWorkflowExecution(array $args = [])
 * @method \GuzzleHttp\Promise\Promise terminateWorkflowExecutionAsync(array $args = [])
 */
class SwfClient extends AwsClient {}
